plugins {
    id 'fabric-loom' version '1.7.4'
}

group = 'nipah'
version = "${mod_version}+${minecraft_version}"
base.archivesName = 'dontdie-fabric'

repositories {
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()
    mods {
        dontdie {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

jar {
    from('../LICENSE') { rename { 'LICENSE_dontdie' } }
}
